# WPdirectory Production Configuration
host: http://localhost/
updateworkers: 4
searchworkers: 6

# Limit to 5000 most recent plugins and 1000 themes for VPS deployment
pluginlimit: 5000
themelimit: 1000

ports:
  http: 8080
  https: 8443

